(self.AMP=self.AMP||[]).push({n:"amp-form",v:"2009282107000",f:(function(AMP,_){
'use strict';var k,aa="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b};function ba(a){for(var b=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global],c=0;c<b.length;++c){var d=b[c];if(d&&d.Math==Math)return}(function(){throw Error("Cannot find global object");})()}ba(this);"function"===typeof Symbol&&Symbol("x");var ca;
if("function"==typeof Object.setPrototypeOf)ca=Object.setPrototypeOf;else{var da;a:{var ea={a:!0},fa={};try{fa.__proto__=ea;da=fa.a;break a}catch(a){}da=!1}ca=da?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ha=ca;
function m(a,b){a.prototype=aa(b.prototype);a.prototype.constructor=a;if(ha)ha(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.Wa=b.prototype}var ia;function p(){return ia?ia:ia=Promise.resolve(void 0)};function ja(a,b){var c=b=void 0===b?"":b;try{return decodeURIComponent(a)}catch(d){return c}};var ka=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;function la(a){var b=Object.create(null);if(!a)return b;for(var c;c=ka.exec(a);){var d=ja(c[1],c[1]),e=c[2]?ja(c[2].replace(/\+/g," "),c[2]):"";b[d]=e}return b};var ma=Object.prototype.toString;function na(a){return a?Array.prototype.slice.call(a):[]};var q=self.AMP_CONFIG||{},oa=("string"==typeof q.cdnProxyRegex?new RegExp(q.cdnProxyRegex):q.cdnProxyRegex)||/^https:\/\/([a-zA-Z0-9_-]+\.)?cdn\.ampproject\.org$/;function pa(a){if(!self.document||!self.document.head||self.location&&oa.test(self.location.origin))return null;var b=self.document.head.querySelector('meta[name="'+a+'"]');return b&&b.getAttribute("content")||null}
var qa={thirdParty:q.thirdPartyUrl||"https://3p.ampproject.net",thirdPartyFrameHost:q.thirdPartyFrameHost||"ampproject.net",thirdPartyFrameRegex:("string"==typeof q.thirdPartyFrameRegex?new RegExp(q.thirdPartyFrameRegex):q.thirdPartyFrameRegex)||/^d-\d+\.ampproject\.net$/,cdn:q.cdnUrl||pa("runtime-host")||"https://cdn.ampproject.org",cdnProxyRegex:oa,localhostRegex:/^https?:\/\/localhost(:\d+)?$/,errorReporting:q.errorReportingUrl||"https://us-central1-amp-error-reporting.cloudfunctions.net/r",betaErrorReporting:q.betaErrorReportingUrl||
"https://us-central1-amp-error-reporting.cloudfunctions.net/r-beta",localDev:q.localDev||!1,trustedViewerHosts:[/(^|\.)google\.(com?|[a-z]{2}|com?\.[a-z]{2}|cat)$/,/(^|\.)gmail\.(com|dev)$/],geoApi:q.geoApiUrl||pa("amp-geo-api")};self.__AMP_LOG=self.__AMP_LOG||{user:null,dev:null,userForEmbed:null};var r=self.__AMP_LOG;function t(){if(!r.user)throw Error("failed to call initLogConstructor");return r.user}function u(){if(r.dev)return r.dev;throw Error("failed to call initLogConstructor");}function v(a,b,c,d){t().assert(a,b,c,d,void 0,void 0,void 0,void 0,void 0,void 0,void 0)};function ra(){var a,b;this.promise=new Promise(function(c,d){a=c;b=d});this.resolve=a;this.reject=b}function sa(a){return new Promise(function(b){b(a())})}function ta(){var a,b;this.xa=new Promise(function(c,d){a=c;b=d});this.Ma=a;this.Ka=b;this.ha=0}ta.prototype.add=function(a){var b=this,c=++this.ha;Promise.resolve(a).then(function(a){b.ha===c&&b.Ma(a)},function(a){b.ha===c&&b.Ka(a)});return this.xa};ta.prototype.then=function(a,b){return this.xa.then(a,b)};var ua=Object.prototype.hasOwnProperty;function w(){return Object.create(null)}function x(a){return a||{}}
function va(a,b){var c=[],d=[];d.push({t:a,s:b,d:0});for(a={};0<d.length;){b=d.shift();a.G=b.t;a.B=b.s;a.Y=b.d;if(c.includes(a.B))throw Error("Source object has a circular reference.");c.push(a.B);a.G!==a.B&&(10<a.Y?Object.assign(a.G,a.B):Object.keys(a.B).forEach(function(a){return function(b){var c=a.B[b];if(ua.call(a.G,b)){var e=a.G[b];if("[object Object]"===ma.call(c)&&"[object Object]"===ma.call(e)){d.push({t:e,s:c,d:a.Y+1});return}}a.G[b]=c}}(a)));a={B:a.B,G:a.G,Y:a.Y}}};function y(){this.Ga=100;this.ga=this.na=0;this.$=Object.create(null)}y.prototype.has=function(a){return!!this.$[a]};y.prototype.get=function(a){var b=this.$[a];if(b)return b.access=++this.ga,b.payload};y.prototype.put=function(a,b){this.has(a)||this.na++;this.$[a]={payload:b,access:this.ga};if(!(this.na<=this.Ga)){u().warn("lru-cache","Trimming LRU cache");a=this.$;var c=this.ga+1,d;for(d in a){var e=a[d].access;if(e<c){c=e;var f=d}}void 0!==f&&(delete a[f],this.na--)}};function z(a,b){return b.length>a.length?!1:0==a.lastIndexOf(b,0)};var wa=x({c:!0,v:!0,a:!0,ad:!0}),xa,ya,za=/[?&]amp_js[^&]*/,Aa=/[?&]amp_gsa[^&]*/,Ba=/[?&]amp_r[^&]*/,Ca=/[?&]amp_kit[^&]*/,Da=/[?&]usqp[^&]*/;
function A(a){xa||(xa=self.document.createElement("a"),ya=self.__AMP_URL_CACHE||(self.__AMP_URL_CACHE=new y));var b=ya,c=xa;if(b&&b.has(a))a=b.get(a);else{c.href=a;c.protocol||(c.href=c.href);var d={href:c.href,protocol:c.protocol,host:c.host,hostname:c.hostname,port:"0"==c.port?"":c.port,pathname:c.pathname,search:c.search,hash:c.hash,origin:null};"/"!==d.pathname[0]&&(d.pathname="/"+d.pathname);if("http:"==d.protocol&&80==d.port||"https:"==d.protocol&&443==d.port)d.port="",d.host=d.hostname;d.origin=
c.origin&&"null"!=c.origin?c.origin:"data:"!=d.protocol&&d.host?d.protocol+"//"+d.host:d.href;b&&b.put(a,d);a=d}return a}function Ea(a,b,c){if(!b)return a;var d=a.split("#",2),e=d[0].split("?",2),f=e[0]+(e[1]?c?"?"+b+"&"+e[1]:"?"+e[1]+"&"+b:"?"+b);return f+=d[1]?"#"+d[1]:""}
function Fa(a){var b=[],c;for(c in a){var d=a[c];if(null!=d)if(Array.isArray(d))for(var e=0;e<d.length;e++){var f=d[e];b.push(encodeURIComponent(c)+"="+encodeURIComponent(f))}else e=d,b.push(encodeURIComponent(c)+"="+encodeURIComponent(e))}return b.join("&")}function Ga(a){"string"==typeof a&&(a=A(a));return qa.cdnProxyRegex.test(a.origin)};function Ha(a){var b="";try{"localStorage"in a&&(b=a.localStorage.getItem("amp-experiment-toggles"))}catch(e){u().warn("EXPERIMENTS","Failed to retrieve experiments from localStorage.")}var c=b?b.split(/\s*,\s*/g):[];a=Object.create(null);for(var d=0;d<c.length;d++)0!=c[d].length&&("-"==c[d][0]?a[c[d].substr(1)]=!1:a[c[d]]=!0);return a};function B(a,b){var c=a.ownerDocument.defaultView,d=c.__AMP_TOP||(c.__AMP_TOP=c),e=c!=d;if(d.__AMP__EXPERIMENT_TOGGLES)var f=d.__AMP__EXPERIMENT_TOGGLES;else{d.__AMP__EXPERIMENT_TOGGLES=Object.create(null);f=d.__AMP__EXPERIMENT_TOGGLES;if(d.AMP_CONFIG)for(var g in d.AMP_CONFIG){var h=d.AMP_CONFIG[g];"number"===typeof h&&0<=h&&1>=h&&(f[g]=Math.random()<h)}if(d.AMP_CONFIG&&Array.isArray(d.AMP_CONFIG["allow-doc-opt-in"])&&0<d.AMP_CONFIG["allow-doc-opt-in"].length&&(g=d.AMP_CONFIG["allow-doc-opt-in"],
h=d.document.head.querySelector('meta[name="amp-experiments-opt-in"]'))){h=h.getAttribute("content").split(",");for(var l=0;l<h.length;l++)-1!=g.indexOf(h[l])&&(f[h[l]]=!0)}Object.assign(f,Ha(d));if(d.AMP_CONFIG&&Array.isArray(d.AMP_CONFIG["allow-url-opt-in"])&&0<d.AMP_CONFIG["allow-url-opt-in"].length)for(g=d.AMP_CONFIG["allow-url-opt-in"],d=la(d.location.originalHash||d.location.hash),h=0;h<g.length;h++)l=d["e-"+g[h]],"1"==l&&(f[g[h]]=!0),"0"==l&&(f[g[h]]=!1)}var n=!!f["ampdoc-fie"];e&&!n?b=Ia(c,
b)?C(c,b):null:(a=D(a),a=E(a),b=Ia(a,b)?C(a,b):null);return b}function F(a,b){a=a.__AMP_TOP||(a.__AMP_TOP=a);return C(a,b)}function G(a,b){var c=D(a);c=E(c);return C(c,b)}function Ja(a,b){return Ka(E(a),b)}function D(a){return a.nodeType?F((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function E(a){a=D(a);return a.isSingleDoc()?a.win:a}function C(a,b){Ia(a,b);a=La(a)[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}
function Ma(a,b){var c=Ka(a,b);if(c)return c;a=La(a);a[b]=Na();return a[b].promise}function Ka(a,b){var c=La(a)[b];if(c){if(c.promise)return c.promise;C(a,b);return c.promise=Promise.resolve(c.obj)}return null}function La(a){var b=a.__AMP_SERVICES;b||(b=a.__AMP_SERVICES={});return b}function Ia(a,b){a=a.__AMP_SERVICES&&a.__AMP_SERVICES[b];return!(!a||!a.ctor&&!a.obj)}
function Na(){var a=new ra,b=a.promise,c=a.resolve;a=a.reject;b.catch(function(){});return{obj:null,promise:b,resolve:c,reject:a,context:null,ctor:null}};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
var Oa=/(\0)|^(-)$|([\x01-\x1f\x7f]|^-?[0-9])|([\x80-\uffff0-9a-zA-Z_-]+)|[^]/g;function Pa(a,b,c,d,e){return e?e:b?"\ufffd":d?a.slice(0,-1)+"\\"+a.slice(-1).charCodeAt(0).toString(16)+" ":"\\"+a};var Qa;function Ra(a,b){for(var c=[],d=a.parentElement;d;d=d.parentElement)b(d)&&c.push(d);return c}function Sa(a){var b="fieldset";/^[\w-]+$/.test(b);b=b.toUpperCase();return Ra(a,function(a){return a.tagName==b})}function H(a,b){for(var c=a.length,d=0;d<c;d++)b(a[d],d)};function Ta(a,b,c){var d=Ja(a,b);if(d)return d;var e=D(a);return e.waitForBodyOpen().then(function(){var a=e.win;var b=e.win.document.head;if(b){var d={};b=b.querySelectorAll("script[custom-element],script[custom-template]");for(var l=0;l<b.length;l++){var n=b[l];n=n.getAttribute("custom-element")||n.getAttribute("custom-template");d[n]=!0}d=Object.keys(d)}else d=[];return d.includes(c)?F(a,"extensions").waitForExtension(a,c):p()}).then(function(){var d=e.win;return d.__AMP_EXTENDED_ELEMENTS&&d.__AMP_EXTENDED_ELEMENTS[c]?
Ma(E(a),b):null})};function I(a){return G(a,"mutator")};var Ua,Va="Webkit webkit Moz moz ms O o".split(" ");function Wa(a,b,c){var d=a.style;if(!z(b,"--")){Ua||(Ua=w());var e=Ua[b];if(!e){e=b;if(void 0===d[b]){var f=b.charAt(0).toUpperCase()+b.slice(1);b:{for(var g=0;g<Va.length;g++){var h=Va[g]+f;if(void 0!==d[h]){f=h;break b}}f=""}void 0!==d[f]&&(e=f)}Ua[b]=e}b=e}b&&(z(b,"--")?a.style.setProperty(b,c):a.style[b]=c)}function Xa(a,b){void 0===b&&(b=a.hasAttribute("hidden"));b?a.removeAttribute("hidden"):a.setAttribute("hidden","")};var J;function Ya(a,b,c){var d=a,e=c;var f=function(a){try{return e(a)}catch(l){throw self.__AMP_REPORT_ERROR(l),l;}};var g=Za();d.addEventListener(b,f,g?void 0:!1);return function(){d&&d.removeEventListener(b,f,g?void 0:!1);f=d=e=null}}function Za(){if(void 0!==J)return J;J=!1;try{var a={get capture(){J=!0}};self.addEventListener("test-options",null,a);self.removeEventListener("test-options",null,a)}catch(b){}return J};function $a(a,b,c,d){var e={detail:c};Object.assign(e,d);if("function"==typeof a.CustomEvent)return new a.CustomEvent(b,e);a=a.document.createEvent("CustomEvent");a.initCustomEvent(b,!!e.bubbles,!!e.cancelable,c);return a}function ab(a,b,c){return Ya(a,b,c)}function bb(a,b){var c=b,d=Ya(a,"mouseup",function(a){try{c(a)}finally{c=null,d()}});return d}function db(a){var b,c=new Promise(function(c){b=bb(a,c)});c.then(b,b);return c};function eb(a,b){function c(c){f=null;e=a.setTimeout(d,100);b.apply(null,c)}function d(){e=0;f&&c(f)}var e=0,f=null;return function(a){for(var b=[],d=0;d<arguments.length;++d)b[d-0]=arguments[d];e?f=b:c(b)}};function fb(a){var b=a.getRootNode();this.S=b.ownerDocument||b;this.j=this.S.defaultView;this.pa=G(a,"viewport");this.U=[];this.U.push(ab(b,"input",function(a){a=a.target;"TEXTAREA"==a.tagName&&a.hasAttribute("autoexpand")&&gb(a)}));this.U.push(ab(b,"mousedown",function(a){1==a.which&&(a=a.target,"TEXTAREA"==a.tagName&&hb(a))}));var c=b.querySelectorAll("textarea");this.U.push(ab(b,"amp:dom-update",function(){c=b.querySelectorAll("textarea")}));var d=eb(this.j,function(a){a.relayoutAll&&ib(c)});this.U.push(this.pa.onResize(d));
jb(c)}function kb(a){function b(){var b=c.querySelector("textarea[autoexpand]");b&&!d?d=new fb(a):!b&&d&&(d.dispose(),d=null)}var c=a.getRootNode(),d=null;Ya(c,"amp:dom-update",b);b()}fb.prototype.dispose=function(){this.U.forEach(function(a){return a()})};
function jb(a){Promise.all(na(a).map(function(a){return lb(a).then(function(b){b&&(t().warn("AMP-FORM",'"textarea[autoexpand]" with initially scrolling content will not autoexpand.\nSee https://github.com/ampproject/amphtml/issues/20839'),a.removeAttribute("autoexpand"))})}))}function lb(a){return I(a).measureElement(function(){return a.scrollHeight>a.clientHeight})}function ib(a){H(a,function(a){"TEXTAREA"==a.tagName&&a.hasAttribute("autoexpand")&&gb(a)})}
function hb(a){var b=I(a);Promise.all([b.measureElement(function(){return a.scrollHeight}),db(a)]).then(function(c){var d=c[0],e=0;return b.measureMutateElement(a,function(){e=a.scrollHeight},function(){d!=e&&a.removeAttribute("autoexpand")})})}
function gb(a){var b=I(a),c=a.ownerDocument.defaultView,d=0,e=0,f=0,g=mb(a);b.measureMutateElement(a,function(){var b=c.getComputedStyle(a)||w();e=a.scrollHeight;var g=parseInt(b.getPropertyValue("max-height"),10);f=isNaN(g)?Infinity:g;d="content-box"==b.getPropertyValue("box-sizing")?-parseInt(b.getPropertyValue("padding-top"),10)+-parseInt(b.getPropertyValue("padding-bottom"),10):parseInt(b.getPropertyValue("border-top-width"),10)+parseInt(b.getPropertyValue("border-bottom-width"),10)},function(){return g.then(function(b){a.classList.toggle("i-amphtml-textarea-max",
b+d>f);if("iAmphtmlHasExpanded"in a.dataset||e<=b)a.dataset.iAmphtmlHasExpanded="",Wa(a,"height",b+d+"px")})})}
function mb(a){var b=a.ownerDocument,c=b.defaultView,d=b.body,e=I(a),f=a.cloneNode(!1);f.classList.add("i-amphtml-textarea-clone");var g=0,h=0,l=!1;return e.measureMutateElement(d,function(){var b=c.getComputedStyle(a)||w(),d=parseInt(b.getPropertyValue("max-height"),10);g=parseInt(b.getPropertyValue("width"),10);l=isNaN(d)||a.scrollHeight<d},function(){l&&(a.scrollTop=0);Wa(f,"width",g+"px");b.body.appendChild(f)}).then(function(){return e.measureMutateElement(d,function(){h=f.scrollHeight},function(){f.parentElement&&
f.parentElement.removeChild(f)})}).then(function(){return h})};function K(a){for(var b=a.elements,c={},d=/^(?:input|select|textarea)$/i,e=/^(?:submit|button|image|file|reset)$/i,f=/^(?:checkbox|radio)$/i,g={},h=0;h<b.length;g={F:g.F},h++){var l=b[h],n=l,dc=n.checked;g.F=n.name;var ec=n.multiple,fc=n.options,gc=n.tagName,cb=n.type;n=n.value;!g.F||nb(l)||!d.test(gc)||e.test(cb)||f.test(cb)&&!dc||(void 0===c[g.F]&&(c[g.F]=[]),ec?H(fc,function(a){return function(b){b.selected&&c[a.F].push(b.value)}}(g)):c[g.F].push(n))}var P=ob(a);P&&P.name&&(a=P.name,void 0===c[a]&&
(c[a]=[]),c[P.name].push(P.value));Object.keys(c).forEach(function(a){0==c[a].length&&delete c[a]});return c}function ob(a){var b=a.elements,c=b.length,d=a.ownerDocument.activeElement,e=null;for(a=0;a<c;a++){var f=b[a],g=f.type;if("BUTTON"==f.tagName||"submit"==g)if(e||(e=f),d==f)return d}return e}function nb(a){if(a.disabled)return!0;a=Sa(a);for(var b=0;b<a.length;b++)if(a[b].disabled)return!0;return!1}
function pb(a){switch(a.type){case "select-multiple":case "select-one":a=a.options;for(var b=0;b<a.length;b++)if(a[b].selected!==a[b].defaultSelected)return!1;break;case "checkbox":case "radio":return a.checked===a.defaultChecked;default:return a.value===a.defaultValue}return!0};function qb(a,b){return a.hasAttribute("verify-xhr")?new rb(a,b):new sb(a)}function L(a){this.h=a}L.prototype.onCommit=function(){tb(this);a:{var a=this.h.elements;for(var b=0;b<a.length;b++){var c=a[b];if(!c.disabled&&!pb(c)){a=!0;break a}}a=!1}return a?this.Aa():Promise.resolve({updatedElements:[],errors:[]})};L.prototype.Aa=function(){return Promise.resolve({updatedElements:[],errors:[]})};function tb(a){(a=a.h.elements)&&H(a,function(a){a.setCustomValidity("")})}
function sb(){L.apply(this,arguments)}m(sb,L);function rb(a,b){this.h=a;this.ba=b;this.X=null;this.wa=[]}m(rb,L);rb.prototype.Aa=function(){var a=this,b=this.ba().then(function(){return[]},function(a){return ub(a)});return vb(this,b).then(function(b){return wb(a,b)})};function vb(a,b){if(!a.X){a.X=new ta;var c=function(){return a.X=null};a.X.then(c,c)}return a.X.add(b)}
function wb(a,b){var c=[],d=a.wa;a.wa=b;for(var e=0;e<b.length;e++){var f=b[e],g=t().assertString(f.name,"Verification errors must have a name property");f=t().assertString(f.message,"Verification errors must have a message property");g=t().assertElement(a.h.querySelector('[name="'+g+'"]'),"Verification error name property must match a field name");g.checkValidity()&&(g.setCustomValidity(f),c.push(g))}var h=d.filter(function(a){return b.every(function(b){return a.name!==b.name})}).map(function(b){return a.h.querySelector('[name="'+
b.name+'"]')});return{updatedElements:c.concat(h),errors:b}}function ub(a){return(a=a.response)?a.json().then(function(a){return a.verifyErrors||[]},function(){return[]}):Promise.resolve([])};function xb(a,b){var c=F(a,"platform");return c.isIos()&&11==c.getMajorVersion()?new yb(b):FormData.prototype.entries&&FormData.prototype.delete?new M(b):new N(b)}function N(a){this.C=a?K(a):w()}N.prototype.append=function(a,b){var c=String(a);this.C[c]=this.C[c]||[];this.C[c].push(String(b))};N.prototype.delete=function(a){delete this.C[a]};
N.prototype.entries=function(){var a=this,b=[];Object.keys(this.C).forEach(function(c){a.C[c].forEach(function(a){return b.push([c,a])})});var c=0;return{next:function(){return c<b.length?{value:b[c++],done:!1}:{value:void 0,done:!0}}}};N.prototype.getFormData=function(){var a=this,b=new FormData;Object.keys(this.C).forEach(function(c){a.C[c].forEach(function(a){return b.append(c,a)})});return b};function M(a){this.D=new FormData(a);a&&(a=ob(a))&&a.name&&this.append(a.name,a.value)}
M.prototype.append=function(a,b){this.D.append(a,b)};M.prototype.delete=function(a){this.D.delete(a)};M.prototype.entries=function(){return this.D.entries()};M.prototype.getFormData=function(){return this.D};function yb(a){M.call(this,a);var b=this;a&&H(a.elements,function(a){"file"==a.type&&0==a.files.length&&(b.D.delete(a.name),b.D.append(a.name,new Blob([]),""))})}m(yb,M);
yb.prototype.append=function(a,b,c){b&&"object"==typeof b&&""==b.name&&0==b.size?this.D.append(a,new Blob([]),c||""):this.D.append(a,b)};var zb={INPUT:!0,SELECT:!0,TEXTAREA:!0};function Ab(a,b){this.h=a;this.j=b;this.R=0;this.K=w();this.oa=null;this.Ca=this.da=!1;this.ma();for(a=0;a<this.h.elements.length;++a)Bb(this,this.h.elements[a]);O(this)}k=Ab.prototype;k.onSubmitting=function(){this.da=!0;O(this)};k.onSubmitError=function(){this.da=!1;O(this)};k.onSubmitSuccess=function(){this.da=!1;this.oa=xb(this.j,this.h).getFormData();this.K=w();this.R=0;O(this)};
function O(a){var b=0<a.R&&!a.da;if(b!==a.Ca){a.h.classList.toggle("amp-form-dirty",b);var c=$a(a.j,"amp:form-dirtiness-change",x({isDirty:b}),{bubbles:!0});a.h.dispatchEvent(c)}a.Ca=b}k.ma=function(){this.h.addEventListener("input",this.va.bind(this));this.h.addEventListener("reset",this.Ja.bind(this));this.h.addEventListener("amp:form-value-change",this.va.bind(this))};k.va=function(a){Bb(this,a.target);O(this)};k.Ja=function(){this.K=w();this.R=0;O(this)};
function Bb(a,b){var c=b.hidden;if(zb[b.tagName]&&b.name&&!c&&!nb(b)){a:switch(b.tagName){case "INPUT":c="checkbox"==b.type||"radio"==b.type?!b.checked:!b.value;break a;case "TEXTAREA":c=!b.value;break a;case "SELECT":c=!1;break a;default:throw Error("isFieldEmpty: "+b.tagName+" is not a supported field element.");}(c=c||pb(b))||(a.oa?(c=b.value,c=a.oa.get(b.name)===c):c=!1);c?(b=b.name,a.K[b]&&(a.K[b]=!1,--a.R)):(b=b.name,a.K[b]||(a.K[b]=!0,++a.R))}};function Cb(){this.o=null}k=Cb.prototype;k.add=function(a){var b=this;this.o||(this.o=[]);this.o.push(a);return function(){b.remove(a)}};k.remove=function(a){this.o&&(a=this.o.indexOf(a),-1<a&&this.o.splice(a,1))};k.removeAll=function(){this.o&&(this.o.length=0)};k.fire=function(a){if(this.o)for(var b=this.o,c=0;c<b.length;c++)(0,b[c])(a)};k.getHandlerCount=function(){return this.o?this.o.length:0};function Db(){this.ua=new Cb}Db.prototype.beforeSubmit=function(a){return this.ua.add(a)};Db.prototype.fire=function(a){this.ua.fire(a)};var Eb=["GET","POST"];function Q(a,b){this.L=a;this.A=b;this.Na="amp-form"}Q.prototype.isEnabled=function(){var a=this.L.getAmpDoc();return a.isSingleDoc()&&a.getRootNode().documentElement.hasAttribute("allow-viewer-render-template")?this.L.hasCapability("viewerRenderTemplate"):!1};Q.prototype.assertTrustedViewer=function(a){return this.L.isTrustedViewer().then(function(b){v(b,"Refused to attempt SSR in untrusted viewer: ",a)})};
Q.prototype.ssr=function(a,b,c,d){var e=this;c=void 0===c?null:c;d=void 0===d?{}:d;var f=c,g=d,h;f||(h=this.A.maybeFindTemplate(a));return this.assertTrustedViewer(a).then(function(){return e.L.sendMessageAwaitResponse("viewerRenderTemplate",Fb(e,b,h,f,g))})};
Q.prototype.applySsrOrCsrTemplate=function(a,b){var c=this;if(this.isEnabled()){v("string"===typeof b.html,"Server side html response must be defined");var d=this.assertTrustedViewer(a).then(function(){return c.A.findAndSetHtmlForTemplate(a,b.html)})}else d=Array.isArray(b)?this.A.findAndRenderTemplateArray(a,b):this.A.findAndRenderTemplate(a,b);return d};
function Fb(a,b,c,d,e){var f=e=void 0===e?{}:e,g=x({type:a.Na}),h=d&&d.successTemplate?d.successTemplate:c;h&&(g.successTemplate={type:"amp-mustache",payload:h.innerHTML});var l=d&&d.errorTemplate?d.errorTemplate:null;l&&(g.errorTemplate={type:"amp-mustache",payload:l.innerHTML});f&&Object.assign(g,f);a=b.xhrUrl;c=b.fetchOpt;b=Object.assign({},c);if((d=c.body)&&"function"==typeof d.getFormData){c=c.body;b.headers["Content-Type"]="multipart/form-data;charset=utf-8";c=c.entries();d=[];for(e=c.next();!e.done;e=
c.next())d.push(e.value);b.body=d}return x({originalRequest:{input:a,init:b},ampComponent:g})};function Gb(a,b){this.la=b;this.pa=G(a,"viewport");this.Ba=F(a.win,"vsync");this.ja=null;this.ia="";this.ea=!1;this.J=a.win.document.createElement("div");Xa(this.J,!1);this.J.classList.add("i-amphtml-validation-bubble");this.J.__BUBBLE_OBJ=this;a.getBody().appendChild(this.J)}Gb.prototype.isActiveOn=function(a){return this.ea&&a==this.ja};Gb.prototype.hide=function(){this.ea&&(this.ea=!1,this.ja=null,this.ia="",this.Ba.run({measure:void 0,mutate:Hb},{bubbleElement:this.J}))};
Gb.prototype.show=function(a,b){this.isActiveOn(a)&&b==this.ia||(this.ea=!0,this.ja=a,this.ia=b,this.Ba.run({measure:Ib,mutate:Jb},{message:b,targetElement:a,bubbleElement:this.J,viewport:this.pa,id:this.la}))};function Hb(a){a.bubbleElement.removeAttribute("aria-alert");a.bubbleElement.removeAttribute("role");for(var b=a.bubbleElement;b.firstChild;)b.removeChild(b.firstChild);Xa(a.bubbleElement,!1)}function Ib(a){a.targetRect=a.viewport.getLayoutRect(a.targetElement)}
function Jb(a){for(var b=a.bubbleElement;b.firstChild;)b.removeChild(b.firstChild);var c=a.bubbleElement.ownerDocument.createElement("div");c.id="bubble-message-"+a.id;c.textContent=a.message;a.bubbleElement.setAttribute("aria-labeledby",c.id);a.bubbleElement.setAttribute("role","alert");a.bubbleElement.setAttribute("aria-live","assertive");a.bubbleElement.appendChild(c);Xa(a.bubbleElement,!0);b=a.bubbleElement;a={top:a.targetRect.top-10+"px",left:a.targetRect.left+a.targetRect.width/2+"px"};for(var d in a)Wa(b,
d,a[d])};var Kb,Lb,Mb=0;function R(a){this.form=a;this.ampdoc=D(a);this.mutator=I(a);this.root=this.ampdoc.getRootNode();this.ca=null}k=R.prototype;k.report=function(){};k.onBlur=function(){};k.onInput=function(){};k.inputs=function(){return this.form.querySelectorAll("input,select,textarea")};
k.checkInputValidity=function(a){if("TEXTAREA"===a.tagName&&a.hasAttribute("pattern")&&(a.checkValidity()||"Please match the requested format."===a.validationMessage)){var b=a.getAttribute("pattern"),c=(new RegExp("^"+b+"$","m")).test(a.value);a.setCustomValidity(c?"":"Please match the requested format.")}return a.checkValidity()};k.checkFormValidity=function(a){Nb(this,a);return a.checkValidity()};k.reportFormValidity=function(a){Nb(this,a);return a.reportValidity()};
function Nb(a,b){H(b.elements,function(b){"TEXTAREA"==b.tagName&&a.checkInputValidity(b)})}k.fireValidityEventIfNecessary=function(){var a=this.ca;this.ca=this.checkFormValidity(this.form);if(a!==this.ca){var b=$a(this.form.ownerDocument.defaultView,this.ca?"valid":"invalid",null,{bubbles:!0});this.form.dispatchEvent(b)}};function Ob(){R.apply(this,arguments)}m(Ob,R);Ob.prototype.report=function(){this.reportFormValidity(this.form);this.fireValidityEventIfNecessary()};
function S(a){R.call(this,a);var b="i-amphtml-validation-bubble-"+Mb++;this.V=new Gb(this.ampdoc,b)}m(S,R);S.prototype.report=function(){for(var a=this.inputs(),b=0;b<a.length;b++)if(!this.checkInputValidity(a[b])){a[b].focus();this.V.show(a[b],a[b].validationMessage);break}this.fireValidityEventIfNecessary()};S.prototype.onBlur=function(a){"submit"!=a.target.type&&this.V.hide()};
S.prototype.onInput=function(a){a=a.target;this.V.isActiveOn(a)&&(this.checkInputValidity(a)?(a.removeAttribute("aria-invalid"),this.V.hide()):(a.setAttribute("aria-invalid","true"),this.V.show(a,a.validationMessage)))};function T(a){R.call(this,a);this.Qa=this.form.id?this.form.id:String(Date.now()+Math.floor(100*Math.random()));this.Fa=0}m(T,R);k=T.prototype;k.reportInput=function(a){var b=Pb(a);b&&this.showValidationFor(a,b)};k.hideAllValidations=function(){for(var a=this.inputs(),b=0;b<a.length;b++)this.hideValidationFor(a[b])};
k.getValidationFor=function(a,b){if(!a.id)return null;var c=a.validationMessage;c="TEXTAREA"===a.tagName&&"customError"===b&&"Please match the requested format."===c?"patternMismatch":b;var d="__AMP_VALIDATION_"+c;d in a||(a[d]=this.root.querySelector("[visible-when-invalid="+c+"][validation-for="+(a.id+"]")));return a[d]};
k.showValidationFor=function(a,b){var c=this.getValidationFor(a,b);if(c){c.textContent.trim()||(c.textContent=a.validationMessage);a.__AMP_VISIBLE_VALIDATION=c;var d=c.getAttribute("id");d||(d="i-amphtml-aria-desc-"+this.Qa+"-"+this.Fa++,c.setAttribute("id",d));a.setAttribute("aria-invalid","true");a.setAttribute("aria-describedby",d);this.mutator.mutateElement(c,function(){return c.classList.add("visible")})}};
k.hideValidationFor=function(a){var b=this.getVisibleValidationFor(a);b&&(delete a.__AMP_VISIBLE_VALIDATION,a.removeAttribute("aria-invalid"),a.removeAttribute("aria-describedby"),this.mutator.mutateElement(b,function(){return b.classList.remove("visible")}))};k.getVisibleValidationFor=function(a){return a.__AMP_VISIBLE_VALIDATION};k.shouldValidateOnInteraction=function(){throw Error("Not Implemented");};
k.onInteraction=function(a){a=a.target;var b=!!a.checkValidity&&this.shouldValidateOnInteraction(a);this.hideValidationFor(a);b&&!this.checkInputValidity(a)&&this.reportInput(a)};k.onBlur=function(a){this.onInteraction(a)};k.onInput=function(a){this.onInteraction(a)};function Qb(){T.apply(this,arguments)}m(Qb,T);Qb.prototype.report=function(){this.hideAllValidations();for(var a=this.inputs(),b=0;b<a.length;b++)if(!this.checkInputValidity(a[b])){this.reportInput(a[b]);a[b].focus();break}this.fireValidityEventIfNecessary()};
Qb.prototype.shouldValidateOnInteraction=function(a){return!!this.getVisibleValidationFor(a)};function U(){T.apply(this,arguments)}m(U,T);U.prototype.report=function(){this.hideAllValidations();for(var a=null,b=this.inputs(),c=0;c<b.length;c++)this.checkInputValidity(b[c])||(a=a||b[c],this.reportInput(b[c]));a&&a.focus();this.fireValidityEventIfNecessary()};U.prototype.shouldValidateOnInteraction=function(a){return!!this.getVisibleValidationFor(a)};function Rb(){T.apply(this,arguments)}m(Rb,T);
Rb.prototype.shouldValidateOnInteraction=function(){return!0};Rb.prototype.onInteraction=function(a){T.prototype.onInteraction.call(this,a);this.fireValidityEventIfNecessary()};function Sb(){U.apply(this,arguments)}m(Sb,U);Sb.prototype.shouldValidateOnInteraction=function(){return!0};Sb.prototype.onInteraction=function(a){U.prototype.onInteraction.call(this,a);this.fireValidityEventIfNecessary()};
function Tb(a){switch(a.getAttribute("custom-validation-reporting")){case "as-you-go":return new Rb(a);case "show-all-on-submit":return new U(a);case "interact-and-submit":return new Sb(a);case "show-first-on-submit":return new Qb(a)}a.ownerDocument&&void 0===Kb&&(Kb=!!document.createElement("form").reportValidity);return Kb?new Ob(a):new S(a)}
function Pb(a){var b=["badInput"];for(c in a.validity)b.includes(c)||b.push(c);var c=b.filter(function(b){return!0===a.validity[b]});return c.length?c[0]:null};function Ub(a){var b=a.ownerDocument.defaultView;b.FormProxy||(b.FormProxy=Vb(b));var c=new b.FormProxy(a);"action"in c||Wb(a,c);a.$p=c}
function Vb(a){function b(a){this.h=a}var c=b.prototype,d=a.Object,e=d.prototype;[a.HTMLFormElement,a.EventTarget].reduce(function(a,b){for(b=b&&b.prototype;b&&b!==e&&!(0<=a.indexOf(b));)a.push(b),b=d.getPrototypeOf(b);return a},[]).forEach(function(b){var d={},f;for(f in b){d.w=a.Object.getOwnPropertyDescriptor(b,f);if(d.w&&f.toUpperCase()!=f&&!z(f,"on")&&!e.hasOwnProperty.call(c,f))if("function"==typeof d.w.value)d.fa=d.w.value,c[f]=function(a){return function(){return a.fa.apply(this.h,arguments)}}(d);
else{var l={};d.w.get&&(l.get=function(a){return function(){return a.w.get.call(this.h)}}(d));d.w.set&&(l.set=function(a){return function(b){return a.w.set.call(this.h,b)}}(d));a.Object.defineProperty(c,f,l)}d={fa:d.fa,w:d.w}}});return b}
function Wb(a,b){var c=a.ownerDocument.defaultView.HTMLFormElement.prototype.cloneNode.call(a,!1),d={},e;for(e in c){d.l=e;if(!(d.l in b||d.l.toUpperCase()==d.l||z(d.l,"on"))){d.m=Xb[d.l];var f=a[d.l];if(d.m)if(d.m.access==V){d.N=void 0;if(f&&f.nodeType){var g=c=f,h=g.nextSibling;g=g.parentNode;g.removeChild(c);try{d.N=a[d.l]}finally{g.insertBefore(c,h)}}else d.N=f;Object.defineProperty(b,d.l,{get:function(a){return function(){return a.N}}(d)})}else d.m.access==W&&(d.O=d.m.attr||d.l,Object.defineProperty(b,
d.l,{get:function(c){return function(){var d=b.getAttribute(c.O);return null==d&&void 0!==c.m.def?c.m.def:c.m.type==Yb?"true"===d:c.m.type==Zb?null!=d:c.m.type==$b?(d=d||"",B(a,"url").parse(d).href):d}}(d),set:function(a){return function(c){a.m.type==Zb&&(c=c?"":null);null!=c?b.setAttribute(a.O,c):b.removeAttribute(a.O)}}(d)}));else Object.defineProperty(b,d.l,{get:function(b){return function(){return a[b.l]}}(d),set:function(b){return function(c){a[b.l]=c}}(d)})}d={N:d.N,O:d.O,m:d.m,l:d.l}}}
var W=1,V=2,$b=1,Yb=2,Zb=3,Xb={acceptCharset:{access:W,attr:"accept-charset"},accessKey:{access:W,attr:"accesskey"},action:{access:W,type:$b},attributes:{access:V},autocomplete:{access:W,def:"on"},children:{access:V},dataset:{access:V},dir:{access:W},draggable:{access:W,type:Yb,def:!1},elements:{access:V},encoding:{access:V},enctype:{access:W},hidden:{access:W,type:Zb,def:!1},id:{access:W,def:""},lang:{access:W},localName:{access:V},method:{access:W,def:"get"},name:{access:W},noValidate:{access:W,
attr:"novalidate",type:Zb,def:!1},prefix:{access:V},spellcheck:{access:W},style:{access:V},target:{access:W,def:""},title:{access:W},translate:{access:W}};function ac(a,b){var c=a.getHeadNode(),d=bc(c,cc(c));if(b){var e=a.getRootNode();if(hc(e,d))b(d);else var f=setInterval(function(){hc(e,d)&&(clearInterval(f),b(d))},4)}}
function bc(a,b){var c=a.__AMP_CSS_SM;c||(c=a.__AMP_CSS_SM=w());var d=ic(a,c,"amp-extension=amp-form");if(d)return d.textContent!==b&&(d.textContent=b),d;var e=(a.ownerDocument||a).createElement("style");e.textContent=b;var f=null;e.setAttribute("amp-extension","amp-form");b=f=ic(a,c,"amp-runtime");(b=void 0===b?null:b)?a.insertBefore(e,b.nextSibling):a.insertBefore(e,a.firstChild);return c["amp-extension=amp-form"]=e}
function ic(a,b,c){return b[c]?b[c]:(a=a.querySelector("style["+c+"]"))?b[c]=a:null}
function cc(a){return(a=a.__AMP_CSS_TR)?a('form.amp-form-submit-error [submit-error],form.amp-form-submit-success [submit-success],form.amp-form-submitting [submitting]{display:block}textarea[autoexpand]:not(.i-amphtml-textarea-max){overflow:hidden!important}.i-amphtml-textarea-clone{visibility:hidden;position:absolute;top:-9999px;left:-9999px;height:0!important}.i-amphtml-validation-bubble{transform:translate(-50%,-100%);background-color:#fff;box-shadow:0 5px 15px 0 rgba(0,0,0,0.5);max-width:200px;position:absolute;display:block;box-sizing:border-box;padding:10px;border-radius:5px}.i-amphtml-validation-bubble:after{content:" ";position:absolute;bottom:-8px;left:30px;width:0;height:0;border-left:8px solid transparent;border-right:8px solid transparent;border-top:8px solid #fff}[visible-when-invalid]{color:red}\n/*# sourceURL=/extensions/amp-form/0.1/amp-form.css*/'):'form.amp-form-submit-error [submit-error],form.amp-form-submit-success [submit-success],form.amp-form-submitting [submitting]{display:block}textarea[autoexpand]:not(.i-amphtml-textarea-max){overflow:hidden!important}.i-amphtml-textarea-clone{visibility:hidden;position:absolute;top:-9999px;left:-9999px;height:0!important}.i-amphtml-validation-bubble{transform:translate(-50%,-100%);background-color:#fff;box-shadow:0 5px 15px 0 rgba(0,0,0,0.5);max-width:200px;position:absolute;display:block;box-sizing:border-box;padding:10px;border-radius:5px}.i-amphtml-validation-bubble:after{content:" ";position:absolute;bottom:-8px;left:30px;width:0;height:0;border-left:8px solid transparent;border-right:8px solid transparent;border-top:8px solid #fff}[visible-when-invalid]{color:red}\n/*# sourceURL=/extensions/amp-form/0.1/amp-form.css*/'}
function hc(a,b){var c=a.styleSheets;for(a=0;a<c.length;a++)if(c[a].ownerNode==b)return!0;return!1};function jc(a){var b=a.documentElement;return["\u26a14email","amp4email"].some(function(a){return b.hasAttribute(a)})};function kc(a,b,c){c=void 0===c?{}:c;var d=void 0===d?!0:d;var e=c;Ta(a,"amp-analytics-instrumentation","amp-analytics").then(function(c){c&&c.triggerEventForTarget(a,b,e,d)})};function lc(a,b){try{return JSON.parse(a)}catch(c){return b&&b(c),null}};var mc=["amp-selector"];
function nc(a,b){var c=this;try{Ub(a)}catch(f){u().error("amp-form","form proxy failed to install",f)}a.__AMP_FORM=this;this.la=b;this.S=a.ownerDocument;this.j=this.S.defaultView;this.Pa=F(this.j,"timer");this.za=B(a,"url-replace");this.ka=null;this.h=a;this.Ea=D(this.h);this.A=F(this.j,"templates");this.qa=F(this.j,"xhr");this.P=B(this.h,"action");this.ta=I(this.h);this.L=G(this.h,"viewer");this.T=new Q(this.L,this.A);this.H=(this.h.getAttribute("method")||"GET").toUpperCase();this.Oa=this.h.getAttribute("target");
this.M=oc(this,"action-xhr");this.Ua=oc(this,"verify-xhr");this.Ha=pc(this);this.ya=!this.h.hasAttribute("novalidate");this.h.setAttribute("novalidate","");this.ya||this.h.setAttribute("amp-novalidate","");this.h.classList.add("i-amphtml-form");this.I="initial";b=this.h.elements;for(var d=0;d<b.length;d++){var e=b[d].name;v("__amp_source_origin"!=e&&"__amp_form_verify"!=e,"Illegal input name, %s found: %s",e,b[d])}this.aa=new Ab(this.h,this.j);this.W=Tb(this.h);this.Ra=qb(this.h,function(){return qc(c)});
this.P.addToAllowlist("FORM",["clear","submit"],["email"]);this.P.installActionHandler(this.h,this.Da.bind(this));this.ma();rc(this);sc(this);this.ra=this.La=this.Ta=null;Ma(E(a),"form-submit-service").then(function(a){c.ra=a});this.Ia=this.S&&jc(this.S)}function oc(a,b){var c=a.h.getAttribute(b);if(c){var d=B(a.h,"url");d.assertHttpsUrl(c,a.h,b);v(!d.isProxyOrigin(c),"form %s should not be on AMP CDN: %s",b,a.h)}return c}
function pc(a){var b=a.h.getAttribute("enctype");if("application/x-www-form-urlencoded"===b||"multipart/form-data"===b)return b;null!==b&&t().warn("amp-form","Unexpected enctype: "+b+". Defaulting to 'multipart/form-data'.");return"multipart/form-data"}k=nc.prototype;k.getXssiPrefix=function(){return this.h.getAttribute("xssi-prefix")};
k.requestForFormFetch=function(a,b,c,d){var e=x({Accept:"application/json"});if("GET"==b||"HEAD"==b){tc(this);var f=K(this.h);d&&d.forEach(function(a){return delete f[a]});c&&va(f,c);var g=Ea(a,Fa(f))}else{g=a;if("application/x-www-form-urlencoded"===this.Ha){var h=Fa(K(this.h));e=x({Accept:"application/json","Content-Type":"application/x-www-form-urlencoded"})}else h=xb(this.j,this.h);d&&d.forEach(function(a){return h.delete(a)});for(var l in c)h.append(l,c[l])}return{xhrUrl:g,fetchOpt:x({body:h,
method:b,credentials:"include",headers:e})}};k.setXhrAction=function(a){this.M=a};k.Da=function(a){var b=this;if(!a.satisfiesTrust(2))return null;if("submit"==a.method)return uc(this).then(function(){return"submitting"!=b.I&&vc(b)?wc(b,a.trust,null):Promise.resolve(null)});"clear"===a.method&&xc(this);return null};function uc(a){if(a.ka)return a.ka;var b=a.h.querySelectorAll(mc.join(",")),c=na(b).map(function(a){return a.whenBuilt()});return a.ka=yc(a,c,2E3)}
k.ma=function(){var a=this;this.Ea.whenNextVisible().then(function(){var b=a.h.querySelector("[autofocus]");if(b)try{b.focus()}catch(c){}});this.h.addEventListener("submit",this.sa.bind(this),!0);this.h.addEventListener("blur",function(b){zc(b.target);a.W.onBlur(b)},!0);this.h.addEventListener("amp:form-value-change",function(b){zc(b.target);a.W.onInput(b)},!0);this.T.isEnabled()||this.h.addEventListener("change",function(b){a.Ra.onCommit().then(function(c){var d=c.errors;c.updatedElements.forEach(zc);
a.W.onBlur(b);"verifying"===a.I&&(d.length?(X(a,"verify-error"),Y(a,x({verifyErrors:d})).then(function(){Ac(a,"verify-error",d,2)})):X(a,"initial"))})});this.h.addEventListener("input",function(b){zc(b.target);a.W.onInput(b)})};function rc(a){Ta(a.h,"inputmask","amp-inputmask").then(function(a){a&&a.install()})}
function Bc(a,b){Cc(a,"Form analytics not supported");var c=x({}),d=K(a.h),e;for(e in d)Object.prototype.hasOwnProperty.call(d,e)&&(c["formFields["+e+"]"]=d[e].join(","));c.formId=a.h.id;kc(a.h,b,c)}
function xc(a){a.h.reset();X(a,"initial");a.h.classList.remove("user-valid");a.h.classList.remove("user-invalid");var b=a.h.querySelectorAll(".user-valid, .user-invalid");H(b,function(a){a.classList.remove("user-valid");a.classList.remove("user-invalid")});var c=a.h.querySelectorAll(".visible[validation-for]");H(c,function(a){a.classList.remove("visible")});Dc(a.h)}
k.sa=function(a){if("submitting"==this.I||!vc(this))return a.stopImmediatePropagation(),a.preventDefault(),Promise.resolve(null);(this.M||"POST"==this.H)&&a.preventDefault();return wc(this,3,a)};
function wc(a,b,c){try{var d={form:a.h,actionXhrMutator:a.setXhrAction.bind(a)};a.ra.fire(d)}catch(l){u().error("amp-form","Form submit service failed: %s",l)}var e=Ec(a),f=a.h.getElementsByClassName("i-amphtml-async-input");a.aa.onSubmitting();if(!a.M&&"GET"==a.H){Cc(a,"Non-XHR GETs not supported.");tc(a);if(0===f.length){for(d=0;d<e.length;d++)a.za.expandInputValueSync(e[d]);Fc(a,!c);a.aa.onSubmitSuccess();return p()}c&&c.preventDefault()}X(a,"submitting");var g=[],h=[];h.push(Gc(a,e));H(f,function(b){var c=
Hc(a,b);b.classList.contains("i-async-require-action")?g.push(c):h.push(c)});return Promise.all(g).then(function(){return yc(a,h,1E4).then(function(){if(a.M)var c=Ic(a,b);else"POST"==a.H?v(!1,"Only XHR based (via action-xhr attribute) submissions are supported for POST requests. %s",a.h):"GET"==a.H&&Fc(a,!0),c=p();return c},function(c){return Jc(a,c,b)})},function(c){return Jc(a,c,b)})}function Jc(a,b,c){var d={};b&&b.message&&(d.error=b.message);return Kc(a,b,d,c)}
function Ec(a){return a.h.querySelectorAll('[type="hidden"][data-amp-replace]')}function qc(a){if("submitting"===a.I)return p();X(a,"verifying");Ac(a,"verify",null,3);return Gc(a,Ec(a)).then(function(){return Lc(a)})}function Ic(a,b){if(a.T.isEnabled())var c=Mc(a,b);else Nc(a,b),c=a.ba(a.M,a.H).then(function(c){return Oc(a,c,b)},function(c){return Pc(a,c,b)});return c}
function Mc(a,b){var c=K(a.h);return Y(a,c).then(function(){return a.P.trigger(a.h,"submit",null,b)}).then(function(){var b=a.requestForFormFetch(a.M,a.H),c=b.fetchOpt||{};var f=c.method;void 0===f?f="GET":(f=f.toUpperCase(),Eb.includes(f));c.method=f;c.headers=c.headers||x({});b.fetchOpt=c;f=b.xhrUrl;c=(c=b.fetchOpt)||{};var g=a.j;g=g.origin||A(g.location.href).origin;f=A(f).origin;g==f&&(c.headers=c.headers||{},c.headers["AMP-Same-Origin"]="true");b.fetchOpt=c;f=a.j;c=b.xhrUrl;if(!1!==b.fetchOpt.ampCors){g=
A(c);g=la(g.search);v(!("__amp_source_origin"in g),"Source origin is not allowed in %s",c);f=f.location.href;"string"==typeof f&&(f=A(f));if(Ga(f)){g=f.pathname.split("/");v(wa[g[1]],"Unknown path prefix in url %s",f.href);var h=g[2],l="s"==h?"https://"+decodeURIComponent(g[3]):"http://"+decodeURIComponent(h);v(0<l.indexOf("."),"Expected a . in origin %s",l);g.splice(1,"s"==h?3:2);g=l+g.join("/");h=(h=f.search)&&"?"!=h?(h=h.replace(za,"").replace(Aa,"").replace(Ba,"").replace(Ca,"").replace(Da,"").replace(/^[?&]/,
""))?"?"+h:"":"";f=g+h+(f.hash||"")}else f=f.href;f=A(f).origin;f=encodeURIComponent("__amp_source_origin")+"="+encodeURIComponent(f);c=Ea(c,f,void 0)}b.xhrUrl=c;return a.T.ssr(a.h,b,Qc(a))}).then(function(c){return Rc(a,c,b)},function(c){var d={};c&&c.message&&(d.error=c.message);return Kc(a,c,d,b)})}
function Qc(a){var b,c=a.h.querySelector("[submit-success]");c&&(b=a.A.maybeFindTemplate(c));var d,e=a.h.querySelector("[submit-error]");e&&(d=a.A.maybeFindTemplate(e));return{successTemplate:b,errorTemplate:d}}function Rc(a,b,c){var d=b.init,e=lc(b.body,function(a){return t().error("amp-form","Failed to parse response JSON: %s",a)});return d&&(d=d.status,300<=d)?Kc(a,d,b,c,e):Sc(a,b,c,e)}
function Nc(a,b){Bc(a,"amp-form-submit");var c=K(a.h);Y(a,c).then(function(){a.P.trigger(a.h,"submit",null,b)})}function Gc(a,b){for(var c=[],d=0;d<b.length;d++)c.push(a.za.expandInputValueAsync(b[d]));return yc(a,c,100)}
function Hc(a,b){return b.getImpl().then(function(a){return a.getValue()}).then(function(c){var d=b.getAttribute("name");d=a.h.querySelector("input[name="+String(d).replace(Oa,Pa)+"]");if(!d){d=x({name:b.getAttribute("name"),hidden:"true"});var e=a.j.document.createElement("input"),f;for(f in d)e.setAttribute(f,d[f]);d=e}d.setAttribute("value",c);a.h.appendChild(d)})}
function Lc(a){var b=na(a.h.querySelectorAll("["+"no-verify".replace(Oa,Pa)+"]")).map(function(a){return a.name||a.id}),c={};return a.ba(a.Ua,a.H,(c.__amp_form_verify=!0,c),b)}k.ba=function(a,b,c,d){Cc(this,"XHRs should be proxied.");a=this.requestForFormFetch(a,b,c,d);return this.qa.fetch(a.xhrUrl,a.fetchOpt)};
function Oc(a,b,c){return a.qa.xssiJson(b,a.getXssiPrefix()).then(function(b){return Sc(a,b,c)},function(a){return t().error("amp-form","Failed to parse response JSON: %s",a)}).then(function(){Bc(a,"amp-form-submit-success");Tc(a,b)})}function Sc(a,b,c,d){X(a,"submit-success");return sa(function(){Y(a,b||{}).then(function(){Ac(a,"submit-success",void 0===d?b:d,c-1);a.aa.onSubmitSuccess()})})}
function Pc(a,b,c){return(b&&b.response?a.qa.xssiJson(b.response,a.getXssiPrefix()).catch(function(){return null}):Promise.resolve(null)).then(function(d){Bc(a,"amp-form-submit-error");Kc(a,b,d,c);Tc(a,b.response)})}function Kc(a,b,c,d,e){X(a,"submit-error");t().error("amp-form","Form submission failed: %s",b);return sa(function(){Y(a,c).then(function(){Ac(a,"submit-error",void 0===e?c:e,d-1);a.aa.onSubmitError()})})}function Fc(a,b){Bc(a,"amp-form-submit");b&&a.h.submit();X(a,"initial")}
function Cc(a,b){var c=a.T.isEnabled();v(!1===c,"[amp-form]: viewerRenderTemplate | %s",b)}function tc(a){var b=a.h.querySelectorAll("input[type=password],input[type=file]");v(0==b.length,"input[type=password] or input[type=file] may only appear in form[method=post]")}function vc(a){void 0===Lb&&(Lb=!!a.j.document.createElement("input").checkValidity);if(Lb){var b=Uc(a.h);if(a.ya)return a.W.report(),b}return!0}
function Tc(a,b){Cc(a,"Redirects not supported.");if(b&&b.headers){var c=b.headers.get("AMP-Redirect-To");if(c){v(!a.Ia,"Redirects not supported in AMP4Email.",a.h);v("_blank"!=a.Oa,"Redirecting to target=_blank using AMP-Redirect-To is currently not supported, use target=_top instead. %s",a.h);try{var d=B(a.h,"url");d.assertAbsoluteHttpOrHttpsUrl(c);d.assertHttpsUrl(c,"AMP-Redirect-To","Url")}catch(e){v(!1,"The `AMP-Redirect-To` header value must be an absolute URL starting with https://. Found %s",
c)}G(a.h,"navigation").navigateTo(a.j,c,"AMP-Redirect-To")}}}function Ac(a,b,c,d){c=$a(a.j,"amp-form."+b,x({response:c}));a.P.trigger(a.h,b,c,d)}function yc(a,b,c){return Promise.race([Promise.all(b),a.Pa.promise(c)])}
function X(a,b){var c=a.I;a.h.classList.remove("amp-form-"+c);a.h.classList.add("amp-form-"+b);var d=a.h.querySelector("["+c+"]");if(d){/^[\w-]+$/.test("i-amphtml-rendered");if(void 0!==Qa)var e=Qa;else{try{var f=d.ownerDocument,g=f.createElement("div"),h=f.createElement("div");g.appendChild(h);e=g.querySelector(":scope div")===h}catch(l){e=!1}e=Qa=e}e?d=d.querySelector("> [i-amphtml-rendered]".replace(/^|,/g,"$&:scope ")):(d.classList.add("i-amphtml-scoped"),e="> [i-amphtml-rendered]".replace(/^|,/g,
"$&.i-amphtml-scoped "),e=d.querySelectorAll(e),d.classList.remove("i-amphtml-scoped"),d=void 0===e[0]?null:e[0]);d&&d.parentElement&&d.parentElement.removeChild(d)}a.I=b}
function Y(a,b){Array.isArray(b)&&(b={},t().warn("amp-form","Unexpected data type: "+b+". Expected non JSON array."));var c=a.h.querySelector("["+a.I+"]"),d=p();if(c){var e="rendered-message-"+a.la;c.setAttribute("role","alert");c.setAttribute("aria-labeledby",e);c.setAttribute("aria-live","assertive");a.A.hasTemplate(c)?d=a.T.applySsrOrCsrTemplate(c,b).then(function(b){if(Array.isArray(b))if(1===b.length)var d=b[0];else d=document.createElement("div"),b.forEach(function(a){return d.appendChild(a)});
else d=b;d.id=e;d.setAttribute("i-amphtml-rendered","");return a.ta.mutateElement(c,function(){c.appendChild(d);var b=$a(a.j,"amp:dom-update",null,{bubbles:!0});c.dispatchEvent(b)})}):a.ta.mutateElement(c,function(){})}return d}
function sc(a){if(!Ga(a.j.location)&&a.h.hasAttribute("data-initialize-from-url")){var b=["SELECT","TEXTAREA"],c="color date datetime-local email hidden month number range search tel text time url week".split(" "),d=["checkbox","radio"],e=function(a,e){if(!a.hasAttribute("data-amp-replace")&&a.hasAttribute("data-allow-initialization")){e=f[e]||"";var g=a.getAttribute("type")||"text",h=a.tagName;"INPUT"===h?c.includes(g.toLocaleLowerCase())?a.value!==e&&(a.value=e):d.includes(g)&&(e=a.value===e,a.checked!==
e&&(a.checked=e)):b.includes(h)&&a.value!==e&&(a.value=e)}},f=la(a.j.location.search);Object.keys(f).forEach(function(b){var c=a.h.elements[b];c&&(c.nodeType===Node.ELEMENT_NODE?e(c,b):c.length&&H(c,function(a){return e(a,b)}))})}}k.Va=function(){return this.La};k.Xa=function(){return this.Ta};function Uc(a){var b=a.querySelectorAll("input,select,textarea,fieldset");H(b,function(a){return Z(a)});return Z(a)}
function Dc(a){var b=document.createElement("input"),c={},d;for(d in b.validity){c.Z=d;var e=a.querySelectorAll("."+String(c.Z).replace(Oa,Pa));H(e,function(a){return function(b){b.classList.remove(a.Z)}}(c));c={Z:c.Z}}}
function Z(a,b){var c=b=void 0===b?!1:b;if(!a.checkValidity)return!0;var d=!1;var e=a.classList.contains("user-valid")?"valid":a.classList.contains("user-invalid")?"invalid":"none";var f=a.checkValidity();"valid"!=e&&f?(a.classList.add("user-valid"),a.classList.remove("user-invalid"),d="invalid"==e):"invalid"==e||f||(a.classList.add("user-invalid"),a.classList.remove("user-valid"),d=!0);if(a.validity)for(var g in a.validity)a.classList.toggle(g,a.validity[g]);if(c&&d){e=Sa(a);for(g=0;g<e.length;g++)Z(e[g]);
a.form&&Z(a.form)}return f}function zc(a){Z(a,!0)}function Vc(a){this.Sa=Wc(a).then(function(){return Xc(a)})}Vc.prototype.whenInitialized=function(){return this.Sa};function Wc(a){var b=new ra;ac(a,b.resolve);return b.promise}function Xc(a){return a.whenReady().then(function(){var b=a.getRootNode();Yc(b.querySelectorAll("form"));kb(a);Zc(b);$c(b)})}function Yc(a){a&&H(a,function(a,c){a.__AMP_FORM||new nc(a,"amp-form-"+c)})}
function Zc(a){a.addEventListener("amp:dom-update",function(){Yc(a.querySelectorAll("form"))})}function $c(a){a.addEventListener("keydown",function(a){if(!a.defaultPrevented&&"Enter"==a.key&&(a.ctrlKey||a.metaKey)&&"TEXTAREA"===a.target.tagName){var b=a.target.form,d=b?b.__AMP_FORM||null:null;d&&(d.sa(a),a.preventDefault())}})}(function(a){a.registerServiceForDoc("form-submit-service",Db);a.registerServiceForDoc("amp-form",Vc)})(self.AMP);
})});

//# sourceMappingURL=amp-form-0.1.js.map
